### ISSUE TITLE
Schematic in Eagle format

### ISSUE THREAD

**Issue by mhoeneveld** [galagaking/espaxa#5]
I really love you project and will now build it to for all 5 AXA window locks. Thanks for the work you did so far.
The schematic is a JPG now in your description. Maybe an idea to put it as schematic file in the code directory too (since the schematic is created in Eagle)
I am thinking of a few adjustments based on the Wemos D1 V4 module and make a print board as well. But let's start with the testing first.

**Comment by galagaking** [comment]
Hi Maurice, thank you for your interest in my project! The schematic is created in EasyEDA, i have uploaded the EasyEDA JSON in the doc directory. Hope this is helpful for you (Eagle is EOL, EasyEDA is free for peronal use).
