### ISSUE TITLE
Not an issue, just a query - open positions on Axa Remote 2.0

### ISSUE THREAD

**Issue by austwhite** [galagaking/espaxa#6]
I love this component and it works flawlessly.
I just wondered if you considered having open positions?

I know the Axa Remote (both original and 2.0 ) do not support position sensing, but was wonderign if you had considered position based on run time.   Such as, it take 30 seconds to fully open a window, assume it takes 15 seconds to get to half open, so to half open have a selection to only run the window for that time.  ( I haven't mesaured times, these are just generic examples ).

I know the Axa Remote doesn't open the windows far even at full open.  This is just an ask to see if it would be considered.
I did see the fork of your project by ellepdesk but I don't want to use MQTT to control the windows, and given I have a few using the ESP8286 D1 Mini, I don't want to rebuild all the hardware to ESP32 to suit the extensive modifications in the fork.

Thanks for all your time and effort.   I appreciate it a lot and I do understand if this request is not a possibility due to constraints of the product.

**Comment by galagaking** [comment]
Hi, my opening gap for my own window is just 5cm. So in my use case it does not make sense to make some steps here. The code from ellepdesk is a complete rewrite (without any hardware reference), it is not that easy to implement this in my code. Sorry for that.
