### ISSUE TITLE
Wemos D1 reboots on opening/closing window

### ISSUE THREAD

**Issue by sydspost** [galagaking/espaxa#8]
Build a PCB conform your scheme, see https://www.sydspost.nl/index.php/2021/03/15/axa-remote-2-0-raamopener-bedienen-vanuit-domotics/ (dutch). Works like a charme. However, on opening or closing the window the Wemos D1 sometime reboots. Not a big deal, but a little bit annoying. I think the AXA draws a lot of current on startup and doesn't leave enough current for the Wemos D1. For powersupply i use a HLK-10M05 AC-DC Power module which provides 2A current. Is this enough ? Is there a way to flatten the startup current withdrawal by the AXA ?

**Comment by galagaking** [comment]
Hi, thank you for your compliments and credits, and using this for a more 'professional' model and adopting this for Domoticz, nice work! If you use these HLK modules (to replace a more stable Raspberry PI power supply as suggested) you should add a decoupling capacitor at the 5V output (22-100uF), close to the Wemos Module. Even a smaller 100nf-220nf in parallel could not do any harm to filter out any noise components. 2A current is sure enough. Be aware of the distance between the 230V AC and DC (5v-8v) pcb traces, there should be preferable a gap between these to prevent flashover. (>10mm).
